#!/usr/bin/env bash
#
# Author: Mathias Fleury
#
# DESCRIPTION: Proof checking for Alethe proofs

PRG="$(basename "$0")"

function usage() {
  echo
  echo "Usage: isabelle $PRG [-d <directory>] [-l imports] [-t base_theory] [-s smt_solver] -i <smt2_problem> -p <alethe_proof>"
  echo
  echo "  Runs the proof reconstruction  on a given SMT problem and Alethe proof."
  echo "  Each problem is allocated at most TIMEOUT seconds."
  echo
  exit 1
}

parse_options() {
    while getopts ":d:l:o:s:p:i:" option; do
        case ${option} in
            d)
                directory_include="${OPTARG}"
		directory_include="-d $directory_include"
                ;;
            l)
                session="${OPTARG}"
                ;;
            t)
                import_session="${OPTARG}"
                ;;
            i)
                smt2="${OPTARG}"
                ;;
            p)
                proof="${OPTARG}"
                ;;
            s)
                solver="${OPTARG}"
                ;;
            \?)
                echo "Invalid option: -$OPTARG" >&2
                ;;
            :)
                echo "Option -$OPTARG requires an argument." >&2
                ;;
        esac
    done
    shift $((OPTIND -1))
}

directory_include=""
session=HOL
import_session=Main
solver=cvc5
parse_options "$@"


[ "$#" -eq 0 -o "$1" = "-?" ] && usage
[ "$smt2"x = "x" ] && usage
[ "$proof"x = "x" ] && usage

SCRATCH="Scratch_${PRG}_$$_${RANDOM}"
SCRATCH_FILE="${SCRATCH}.thy"

TIMEOUT=$1
shift

$ISABELLE_HOME/bin/isabelle build ${directory_include} -b $session

echo -e "theory $SCRATCH\n\timports \"$import_session\"\nbegin\n\
 check_smt (\"$solver\") \"$smt2\" \"$proof\"\nend" \
 > ${SCRATCH_FILE}

cat ${SCRATCH_FILE}
$ISABELLE_HOME/bin/isabelle process_theories $directory_include -O -U -v -l $session -f "${SCRATCH_FILE}" "${SCRATCH}"

echo "deleting theory file"
rm ${SCRATCH_FILE}

